### ISSUE TITLE
Export with transparent background (request)

### ISSUE THREAD

**Issue by Sphynxcolt** [bean-mhm/realbloom#10]
Hey, I was wondering if there is a way to export as a png with a transparent background. Would be very helpful to be able to, so it could be used in other software more efficiently.

**Comment by bean-mhm** [comment]
Hi. Have you tried enabling the "Transparency" checkbox in the input transform settings? For example, if you're working with the Diffraction module, open *Input Transform* and in the *GENERAL* section enable *Transparency*.

**Comment by Sphynxcolt** [comment]
Oh my god I am still using an old version... I didnt even realize it was still 0.5.0 Alpha.... Will update asap, Im so sorry for this stupid question haha

**Comment by bean-mhm** [comment]
Your question is not stupid lol. Feel free to join the [discord server](https://discord.gg/Xez5yec8Hh) to be notified for new releases!

**Comment by Sphynxcolt** [comment]
Okay so I did enable transparency and then ran the diffraction (also the dispersion), with the transparent checkbox enabled. Now when I want to save the texture, it still shows with a black background.

Just the diffraction
![transparent2](https://github.com/bean-mhm/realbloom/assets/56783893/38fb124f-c738-4cba-a2a4-fb22a3687793)

with dispersion
![transparent](https://github.com/bean-mhm/realbloom/assets/56783893/eb3f7a7d-1c68-45b9-8f62-57d50b08b43c)

(0.7.0 Beta)

**Comment by bean-mhm** [comment]
I should mention that all three modules work with RGB data only. At the time of writing them, I couldn't think of a case where having an extra alpha channel would be useful. In Diffraction, for example, 3 FFTs are performed on each color channel R, G, and B. After dispersion, you can use the diffraction pattern for convolution, or use additive blending in other software if you just want to blend it with another image.

**Comment by Sphynxcolt** [comment]
Fair enough. Using addition in other software seems to be the way. Thanks for the infos 👍
