### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by mxsage** [bean-mhm/realbloom#8]
To compile on VS22 I had to change some input paths:
#include <ocio/OpenColorIO.h> --> #include "ocio/OpenColorIO.h"
and
#include "OpenImageIO/imageio.h" --> #include "oiio/imageio.h"

Additionally I added a return value to CMImageIO::init() in CmImageIO.cpp

And lastly I had to drag dlls to the executable folder.

Then it worked great!

![dlls](https://user-images.githubusercontent.com/10853611/231600752-01af7c29-f991-4c1d-96ac-556c884bf041.PNG)

**Comment by mxsage** [comment]
See my changes here: https://github.com/mxsage/realbloom/commit/b64b81d528149e7f844bd914ba7331f4693ac9ad

**Comment by bean-mhm** [comment]
Hey, thanks for informing! The issues mentioned have been solved in the dev branch and will soon be merged to main.
